title: Introduction to Raspberry Pi Pico guide
hero_image: images/banner.png
description: introduction-to-the-pico description
version: 4
listed: false
copyedit: false
last_tested: "2022-01-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
